#!name=Wink
#!desc=Wink Vip
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/.png
#!homepage=https://whatshub.top
#!author=Khong Manh Yen (Kthy)
[Script]
WinkForeverVipCrack.js=type=http-response,pattern=^https?:\/\/api-sub\.meitu\.com\/v2\/user\/vip_info_by_group\.json,requires-body=1,script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/WinkForeverVipCrack.js


[MITM]
hostname = %APPEND% api-sub.meitu.com
